spring:
  application:
    name: SoftLi

am:
  database: AppDBProxy - Override
  
  
license-model-values:
  licenseModelTemplates:
    -
      id: 'OM-1'         # WAS ND
      metric: 'vCPU'
      category: 'Application'
    -
      id: 'OM-2'         # RHEL
      metric: 'Instance'
      category: 'Infrastructure'
    -
      id: 'OM-3'         # Mongo DB
      metric: 'Instance'
      category: 'Application'
    -
      id: 'OM-4'         # Qualys
      metric: 'Instance'
      category: 'Infrastructure'
    -
      id: 'OM-5'         # Kafka
      metric: 'vCPU'
      category: 'Application'
      
      
license-rights-values:
  licenseRightTemplates:
    -
      appId: 'A-1'
      modelId: 'OM-1'
      quantity: '32'
    -
      appId: 'A-2'
      modelId: 'OM-1'
      quantity: '16'
    -
      appId: 'A-2'
      modelId: 'OM-5'
      quantity: '64'
    -
      appId: 'A-3'
      modelId: 'OM-3'
      quantity: '3'

manifest-values:
  manifestTemplates:
    -
      imageId: 'I-1'
      swReleaseId: 'OM-1'
    -
      imageId: 'I-1'
      swReleaseId: 'OM-2'
    -
      imageId: 'I-1'
      swReleaseId: 'OM-4'
    -
      imageId: 'I-2'
      swReleaseId: 'OM-2'
    -
      imageId: 'I-2'
      swReleaseId: 'OM-4'
    -
      imageId: 'I-2'
      swReleaseId: 'OM-3'
    -
      imageId: 'I-3'
      swReleaseId: 'OM-1'
    -
      imageId: 'I-3'
      swReleaseId: 'OM-2'
    -
      imageId: 'I-3'
      swReleaseId: 'OM-4'
    -
      imageId: 'I-3'
      swReleaseId: 'OM-5'
